server:
  port: 8881
  undertow:
    accesslog:
      # 是否启动日志
      enabled: true
      # 日志文件名后缀
      suffix: log
      # 日志文件名前缀
      prefix: undertow_log
      dir: c:/logs/
    # HTTP POST请求最大的大小
    max-http-post-size: 0
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    io-threads: 16
    # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
    worker-threads: 128
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分
    buffer-size: 1024
    # 是否分配的直接内存
    direct-buffers: true
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/self?autoReconnect=true
    username: root
    password: root
    sql-script-encoding: utf-8
    #连接池的配置信息
    hikari:
      connection-timeout: 30000
      maxLifetime: 1800000
      maximum-pool-size: 100
      minimum-idle: 10
      validation-timeout: 5000
      login-timeout: 30
      idle-timeout: 30000
      auto-commit: true
      connection-test-query: SELECT 1
      pool-name: HikariPool
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mapper/*.xml

pagehelper:
  offset-as-page-num: true
  row-bounds-with-count: true
  reasonable: true
  helper-dialect: mysql
  params: count=countSql
  support-methods-arguments: true
logging:
  file:
    max-size: 100MB
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss:SSS
  path: c:\logs
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8783/eureka/,http://127.0.0.1:8592/eureka/
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 3
#暴露health
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

      ##    url: jdbc:mariadb://mariadb.nat123.cc:33062/vinycrm?autoReconnect=true
      ##    username: vinyCRM
      ##    password: viny123