server:
  port: 10086
  undertow:
    accesslog:
      # 是否启动日志
      enabled: false
      # 日志文件名后缀
      suffix: log
      # 日志文件名前缀
      prefix: undertow_log
      dir: /Users/xiaoxiong/logs/
    # HTTP POST请求最大的大小
    max-http-post-size: 0
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分
    buffer-size: 2048
    # 是否分配的直接内存
    direct-buffers: true
    threads:
      # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
      io: 16
      # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
      worker: 1000
spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://111.230.209.59:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
#    username: root
#    password: gshjd123
#    sql-script-encoding: utf-8
#    #连接池的配置信息
#    hikari:
#      connection-timeout: 3000
#      maxLifetime: 30000
#      maximum-pool-size: 100
#      minimum-idle: 100
#      validation-timeout: 3000
#      login-timeout: 3
#      auto-commit: true
#      connection-test-query: SELECT 1
#      pool-name: HikariPool
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    open-in-view: false

#   redis配置
  redis:
#    连接地址
    host: 192.168.100.166
#    端口
    port: 6379
    database: 7
#    redis密码
    password: root
    jedis:
      pool:
#        最大连接数（负值为没有限制）
        max-active: 1000
#        连接池最大空闲连接数
        max-idle: 1000
#        连接池最长阻塞时间（负值为没有限制）
        max-wait: 3000
#        连接池最小空闲连接数
        min-idle: 1000
#    redis超时时间（毫秒）
    timeout: 3000
  servlet:
    multipart:
      max-file-size: 10MB
      location: ${java.io.tmpdir}
#mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
#  mapper-locations: classpath:mapper/*/*.xml

logging:
  config: classpath:log/logback-spring.xml


#pagehelper:
#  offset-as-page-num: true
#  row-bounds-with-count: true
#  reasonable: true
#  helper-dialect: mysql
#  params: count=countSql
#  support-methods-arguments: true